"""create opportunity searches table

Revision ID: 7b0558d0c2bd
Revises: 
Create Date: 2026-10-03 13:13:26.320149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b0558d0c2bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_searches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('target_customer', sa.String(length=300), nullable=False),
    sa.Column('objective', sa.String(length=1000), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('initial_hypothesis', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('created', name='opportunity_search_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity_searches')
    postgresql.ENUM(
        name="opportunity_search_status",
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
